feat(ex00): implement BitcoinExchange class and data download
Added BitcoinExchange class to process BTC price data from CSV.
Implemented data.csv download and extraction from provided URL.
Updated Makefile to handle new source files and data dependency.

diff --git a/ex00/Makefile b/ex00/Makefile
--- a/ex00/Makefile
+++ b/ex00/Makefile
@@ -1,9 +1,10 @@
 
 
-NAME = easyfind
+NAME = btc
+DATAURL = https://cdn.intra.42.fr/document/document/38604/cpp_09.tgz
 
-SRC = main.cpp
-DEPS = easyfind.hpp
+SRC = main.cpp BitcoinExchange.cpp
+DEPS = BitcoinExchange.hpp
 
 VPATH = sources includes
 OBJ_PATH = obj/
@@ -19,7 +20,7 @@ UP = "\033[A"
 CUT = "\033[K"
 
 
-all: $(NAME)
+all: $(NAME) data.csv
 
 
 $(NAME): $(OBJ)
@@ -31,11 +32,23 @@ $(OBJ_PATH)%.o: %.cpp $(DEPS)
 	$(CC) $(FLAGS) -c $< -o $@ -I $(DEPS_PATH)
 	@echo -n $(UP)$(CUT)
 
+data.csv:
+	@if [ -f cpp_09.tgz ]; then \
+		echo "cpp_09.tgz already exists"; \
+	else \
+		echo "Downloading cpp_09.tgz..."; \
+		wget -q $(DATAURL) || { echo "Failed to download cpp_09.tgz"; exit 0; }; \
+	fi; \
+	echo -n $(UP)$(CUT); \
+	tar --strip-components=1 -xf cpp_09.tgz cpp_09/data.csv; \
+	echo "data.csv extracted from ${DATAURL}"; \
+	rm -f cpp_09.tgz
+
 clean:
 	rm -rf $(OBJ_PATH)
 
 fclean: clean
-	rm -f $(NAME)
+	rm -f $(NAME) data.csv cpp_09.tgz
 
 re: fclean all
 
